# Depenizen config

# Bungee server address (if any). Exclude the port.
# For example: "localhost"
# Use "none" to disable Bungee support functionality.
Bungee server address: none
# Set to the bungee server's primary port (if in use).
Bungee server port: 25565

# Settings related to the server-side support of the Clientizen mod, a mod providing client-side scripting & integration with servers running Denizen (and Depenizen).
# For more information, see the GitHub repository: https://github.com/tal5/Clientizen
Clientizen:
  # Whether server-side Clientizen support should be enabled.
  # This controls things like the server sending Clientizen clients scripts, receiving events from clients, etc.
  # Disabling this setting will override all other Clientizen settings.
  enabled: false
