name: Depenizen
authors: ['The DenizenScript Team']
version: ${project.version} (build ${BUILD_NUMBER})
main: com.denizenscript.depenizen.bukkit.Depenizen
depend: [Denizen]

api-version: '1.13'

softdepend:
    - AreaShop
    - AriKeys
    - ASkyBlock
    - BetonQuest
    - BigDoors
    - BossShopPro
    - BreweryX
    - CoreProtect
    - CrackShot
    - EffectLib
    - Essentials
    - Factions
    - GriefPrevention
    - Jobs
    - LibsDisguises
    - LuckPerms
    - MagicSpells
    - mcMMO
    - MobArena
    - MythicKeysPlugin
    - MythicMobs
    - NoCheatPlus
    - NoteBlockAPI
    - OpenTerrainGenerator
    - PlaceholderAPI
    - PlayerPoints
    - PlotSquared
    - PVPArena
    - PVPStats
    - Quests
    - Residence
    - Sentinel
    - Shopkeepers
    - SkillAPI
    - TerrainControl
    - Towny
    - TownyChat
    - Vampire
    - ViaVersion
    - Vivecraft-Spigot-Extensions
    - Votifier
    - WorldEdit
    - WorldGuard
