name: Depenizen
authors: [GnomeffinWay, Morphan1]
version: ${project.version} (build ${BUILD_NUMBER})
main: net.gnomeffinway.depenizen.Depenizen
depend: [Denizen]
softdepend: [mcMMO, BattleNight, Towny, Factions, Votifier, Jobs, Heroes, pvparena, Dynmap, WorldEdit, WorldGuard, Essentials, pvpstats, HyperConomy, SkillAPI, Prism, ProtocolSupport, MythicMobs]

commands:
    depenizen:
        description: Prints out the current Depenizen version.
        usage: /depenizen

permissions: {}
