name: Depenizen
author: GnomeffinWay
version: ${project.version} (build ${BUILD_NUMBER})
main: net.gnomeffinway.depenizen.Depenizen
depend: [Denizen]
softdepend: [mcMMO, BattleNight, Towny, Factions, Votifier, Jobs, Heroes, pvparena, Dynmap, WorldEdit, WorldGuard, Essentials, pvpstats, HyperConomy, SkillAPI]

commands:
    depenizen:
        description: Prints out the current Depenizen version.
        usage: /depenizen

permissions: {}
