name: Depenizen
authors: ['Morphan1', 'DenizenScript team']
version: ${project.version} (build ${BUILD_NUMBER})
main: com.denizenscript.depenizen.bukkit.DepenizenPlugin
depend: [Denizen]
softdepend: [mcMMO, BattleNight, Towny, Factions, Votifier, Jobs, Heroes, pvparena, WorldEdit, WorldGuard, Essentials, pvpstats, HyperConomy, SkillAPI, Prism, TerrainControl, PlotMe, PlotSquared, SimpleClans, MobArena, ASkyBlock, NoCheatPlus, MythicMobs, Sentinel, ShopKeepers, GriefPrevention, Quests, PlaceholderAPI, Residence, dtlTraders, AreaShop, LibsDisguises, OpenTerrainGenerator, PlayerPoints, LuckPerms, EffectLib, BossShop, Vampire]

commands:
    depenizen:
        description: Prints out the current Depenizen version.
        usage: /depenizen
        permission: depenizen.command

permissions: {}
